flower=read.csv("flower.csv",header=FALSE)
fl=as.matrix(flower)
 flv=as.vector(fl)
 distance=dist(flv,method="euclidean")
 clusterf=hclust(distance,method="ward.D")
plot(clusterf )
rect.hclust(clusterf,k=3,border="red")
> flowerclust=cutree(clusterf,k=3)
tapply(flv,flowerclust,mean)
 dim(flowerclust)=c(50,50)
image(flowerclust,axes=FALSE)
image(fl,axes=FALSE)
image(fl,axes=FALSE,col=grey(seq(0,1,length=256)))